version: 2
jobs:
    build:
        working_directory: /elasticmq
        docker:
            - image: docker:17.07.0-ce-git
        steps:
            - checkout
            - setup_remot_docker
            - run:
                name: Install dependencies
                command: |
                    echo "install"
            - restore_cache:
                keys:


version: 2.0
jobs:
    checkout:
        working_directory: /elasticmq
        docker:
            - image: docker:17.07.0-ce-git

        steps:
            - checkout
            - setup_remote_docker

    build_latest:
        working_directory: /elasticmq
        docker:
            - image: docker:17.07.0-ce-git

        steps:
            - run: echo $CIRCLE_SHA1 > .circle-sha
            - restore_cache:
                keys:
                    - elasticmq-{{ checksum ".circle-sha" }}
                paths:
                    - /caches/elasticmq.tar
            - run:
                name: Load Docker image layer cache
                command: |
                    set +o pipefails
                    docker load -i /caches/elasticmq.tar
            - run:
                name: Build ElasticMQ Docker image
                command: |
                    docker build --cache-from=elasticmq elasticmq images/latest
            - run:
                name: Save Docker image layer cache
                command: |
                    mkdir -p /caches
                    docker save -o /caches/elasticmq.tar elasticmq
            - save_cache:
                key: elasticmq-{{ checksum ".circle-sha" }}
                paths:
                    - /caches/elasticmq.tar

    build_tag:
        working_directory: /elasticmq
        docker:
            - image: docker:17.07.0-ce-git

        steps:
            - run: echo $CIRCLE_SHA1 > .circle-sha
            - restore_cache:
                keys:
                    - elasticmq-{{ checksum ".circle-sha" }}
                paths:
                    - /caches/elasticmq.tar
            - run:
                name: Load Docker image layer cache
                command: |
                    set +o pipefails
                    docker load -i /caches/elasticmq.tar
            - run:
                name: Build ElasticMQ Docker image
                command: |
                    docker build --cache-from=elasticmq elasticmq "images/$CIRCLE_TAG"

    test:
        working_directory: /elasticmq
        docker:
            - image: docker:17.07.0-ce-git
        steps:
            - run: echo $CIRCLE_SHA1 > .circle-sha
            - restore_cache:
                keys:
                    - elasticmq-{{ checksum ".circle-sha" }}
                paths:
                    - /caches/elasticmq.tar
            - run:
                name: Test Docker image
                command: |
                    echo "Test"

    deploy:
        docker:
            - image: docker:17.07.0-ce-git
        steps:
            - run: echo $CIRCLE_SHA1 > .circle-sha
            - restore_cache:
                keys:
                    - elasticmq-{{ checksum ".circle-sha" }}
            - run:
                name: "Trigerring auto build on Docker hub"
                command: |
                    echo "Trigger"

workflows:
    version: 2

    build_and_deploy:
        jobs:
            - checkout
            - build_latest:
                requires:
                    - checkout
            - build_tag:
                requires:
                    - checkout
                filters:
                    tags:
                        only: /\d+(\.\d+){2}/
                    branches:
                        only: master

            - test:
                requires:
                    - dependencies

            - deploy:
                requires:
                    - build_tag
                filters:
                    tags:
                        only: /\d+(\.\d+){2}/
                    branches:
                        only: master
